/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "FileServer.h"
#include <string.h>

char **
getfile_1_svc(flName *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}


int main (int argc, char * argv[])

	return 0;
}
