/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "FileServer.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "NameServer.h"
#include <sys/types.h>
#include <unistd.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#include <string.h>

static void
file_server_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		flName getfile_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case getFile:
		_xdr_argument = (xdrproc_t) xdr_flName;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) getfile_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	/*Running file server as a client of NameServer first*/
	CLIENT *clnt;
	char name[256] = "FileServer";
	regName ops;

	if (argc!= 2) {
    fprintf(stderr,"Usage: %s Host Name\n",argv[0]);
    exit(0);
  }

	/*Creating Client*/
	clnt = clnt_create(argv[1], NAME_SERVER, NAME_VERSION, "udp");

	/* Make sure the create worked */
  if (clnt == (CLIENT *) NULL) {
    clnt_pcreateerror(argv[1]);
    exit(1);
  }

	ops.name = name;
	ops.hostname = argv[1];

	/*Register host to name server*/
	if(*registerserver_1(&ops, clnt) == -1){
		printf("%s\n", "Failed to register host name with NameServer");
		exit(1);
	}

	/*Running FileServer as a server to client*/
	if(fork() == 0){

	register SVCXPRT *transp;

	pmap_unset (FILE_SERVER, FILE_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, FILE_SERVER, FILE_VERSION, file_server_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FILE_SERVER, FILE_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, FILE_SERVER, FILE_VERSION, file_server_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FILE_SERVER, FILE_VERSION, tcp).");
		exit(1);
	}

	printf("%s\n", "Running FileServer...");
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
	}
}
