/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "FileServer.h"
#include <string.h>

char **
getfile_1_svc(flName *argp, struct svc_req *rqstp)
{
	static char * result;
	result = (char*)malloc(1000*10000*sizeof(char*));

	FILE *fp = fopen(argp->name, "r");
	char buff[1000];

	/*Checking that file was openeded*/
	if (fp == NULL){
		 printf("Could not open file.\n");
		 return &result;
	}


	/*Reading file into the result string*/
	while(fgets(buff, 1000, fp)){
		strcat(result, buff);
	}

	return &result;
}
