/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "NameServer.h"
#include <string.h>

bool_t
xdr_regName (XDR *xdrs, regName *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->name, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->hostname, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_remName (XDR *xdrs, remName *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->name, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getName (XDR *xdrs, getName *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->name, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
