/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NAMESERVER_H_RPCGEN
#define _NAMESERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include <string.h>

struct regName {
	char *name;
	char *hostname;
};
typedef struct regName regName;

struct remName {
	char *name;
};
typedef struct remName remName;

struct getName {
	char *name;
};
typedef struct getName getName;

#define NAME_SERVER 33333333
#define NAME_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define registerServer 1
extern  int * registerserver_1(regName *, CLIENT *);
extern  int * registerserver_1_svc(regName *, struct svc_req *);
#define removeServer 2
extern  int * removeserver_1(remName *, CLIENT *);
extern  int * removeserver_1_svc(remName *, struct svc_req *);
#define getServerHostName 3
extern  char ** getserverhostname_1(getName *, CLIENT *);
extern  char ** getserverhostname_1_svc(getName *, struct svc_req *);
extern int name_server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registerServer 1
extern  int * registerserver_1();
extern  int * registerserver_1_svc();
#define removeServer 2
extern  int * removeserver_1();
extern  int * removeserver_1_svc();
#define getServerHostName 3
extern  char ** getserverhostname_1();
extern  char ** getserverhostname_1_svc();
extern int name_server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_regName (XDR *, regName*);
extern  bool_t xdr_remName (XDR *, remName*);
extern  bool_t xdr_getName (XDR *, getName*);

#else /* K&R C */
extern bool_t xdr_regName ();
extern bool_t xdr_remName ();
extern bool_t xdr_getName ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NAMESERVER_H_RPCGEN */
